# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        shell: bash
        env:
          RCLONE_FTP_USER: ${{ secrets.RCLONE_FTP_USER }}
          RCLONE_FTP_HOST: ${{ secrets.RCLONE_FTP_HOST }}
          RCLONE_FTP_PORT: ${{ secrets.RCLONE_FTP_PORT }}
          RCLONE_FTP_PASS: ${{ secrets.RCLONE_FTP_PASS }}
        run: |
          curl https://rclone.org/install.sh | sudo bash

          rclone sync -i ./behavior behavior_packs/Pets

          for f in addons/*; do
            rclone sync -i ./addons/$f/behavior behavior_packs/$f
            rclone sync -i ./addons/$f/resource resource_packs/$f
          done

          rclone copy world worlds/Legoland
          rclone copy settings .
